cmake_minimum_required(VERSION 3.10)
project(dk)
# 1. 声明为一个纯头文件库 (INTERFACE)
add_library(dk INTERFACE)
target_include_directories(dk INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_compile_features(dk INTERFACE cxx_std_17)
# 2. 开关：默认不编译测试 (当被 ROS 引入时)
option(DK_BUILD_TESTS "Build DK framework tests" OFF)
if(DK_BUILD_TESTS)
    enable_testing()
    add_subdirectory(tests)
endif()